#!/bin/sh

# PROVIDE: RioCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# RioCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable RioCoin service.
# RioCoin_config (path): Set to /usr/local/etc/RioCoin.conf by default.
# RioCoin_user:  The user account RioCoin daemon runs as. It uses 'root' user by default.
# RioCoin_group: The group account RioCoin daemon runs as. It uses 'wheel' group by default.
# RioCoin_datadir (str): Default to "/var/db/RioCoin". Base data directory.

. /etc/rc.subr

name=RioCoin
rcvar=RioCoin_enable

: ${RioCoin_enable:=NO}
: ${RioCoin_config=/usr/local/etc/RioCoin.conf}
: ${RioCoin_datadir=/var/db/RioCoin}
: ${RioCoin_user="root"}
: ${RioCoin_group="wheel"}

required_files=${RioCoin_config}
command=/usr/local/bin/RioCoind
RioCoin_chdir=${RioCoin_datadir}
pidfile="${RioCoin_datadir}/RioCoind.pid"
stop_cmd=RioCoin_stop
command_args="-conf=${RioCoin_config} -datadir=${RioCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

RioCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${RioCoin_datadir}
	[ $? -eq 0 ] && chown -R ${RioCoin_user}:${RioCoin_group} ${RioCoin_datadir}
}

RioCoin_prestart()
{
	if [ ! -d "${RioCoin_datadir}/." ]; then
		RioCoin_create_datadir || return 1
	fi
}

RioCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

RioCoin_stop()
{
    RioCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${RioCoin_config} -datadir=${RioCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
